/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWrittenRouteImport } from './routes/_authenticated.written'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated.tracker'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated.pricing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated.practice.index'
import { Route as AuthenticatedModelTestIndexRouteImport } from './routes/_authenticated.model-test.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedPracticeSlugRouteImport } from './routes/_authenticated.practice.$slug'
import { Route as AuthenticatedModelTestIdRouteImport } from './routes/_authenticated.model-test.$id'
import { Route as AuthenticatedAdminTestsRouteImport } from './routes/_authenticated.admin.tests'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated.admin.questions'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWrittenRoute = AuthenticatedWrittenRouteImport.update({
  id: '/written',
  path: '/written',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelTestIndexRoute =
  AuthenticatedModelTestIndexRouteImport.update({
    id: '/model-test/',
    path: '/model-test/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPracticeSlugRoute =
  AuthenticatedPracticeSlugRouteImport.update({
    id: '/practice/$slug',
    path: '/practice/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelTestIdRoute =
  AuthenticatedModelTestIdRouteImport.update({
    id: '/model-test/$id',
    path: '/model-test/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTestsRoute = AuthenticatedAdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/written': typeof AuthenticatedWrittenRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/model-test/$id': typeof AuthenticatedModelTestIdRoute
  '/practice/$slug': typeof AuthenticatedPracticeSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/model-test/': typeof AuthenticatedModelTestIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/written': typeof AuthenticatedWrittenRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/model-test/$id': typeof AuthenticatedModelTestIdRoute
  '/practice/$slug': typeof AuthenticatedPracticeSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/model-test': typeof AuthenticatedModelTestIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/written': typeof AuthenticatedWrittenRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/_authenticated/model-test/$id': typeof AuthenticatedModelTestIdRoute
  '/_authenticated/practice/$slug': typeof AuthenticatedPracticeSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/model-test/': typeof AuthenticatedModelTestIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/pricing'
    | '/tracker'
    | '/written'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/tests'
    | '/model-test/$id'
    | '/practice/$slug'
    | '/admin/'
    | '/model-test/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/tracker'
    | '/written'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/tests'
    | '/model-test/$id'
    | '/practice/$slug'
    | '/admin'
    | '/model-test'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/pricing'
    | '/_authenticated/tracker'
    | '/_authenticated/written'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tests'
    | '/_authenticated/model-test/$id'
    | '/_authenticated/practice/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/model-test/'
    | '/_authenticated/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/written': {
      id: '/_authenticated/written'
      path: '/written'
      fullPath: '/written'
      preLoaderRoute: typeof AuthenticatedWrittenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-test/': {
      id: '/_authenticated/model-test/'
      path: '/model-test'
      fullPath: '/model-test/'
      preLoaderRoute: typeof AuthenticatedModelTestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/practice/$slug': {
      id: '/_authenticated/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof AuthenticatedPracticeSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-test/$id': {
      id: '/_authenticated/model-test/$id'
      path: '/model-test/$id'
      fullPath: '/model-test/$id'
      preLoaderRoute: typeof AuthenticatedModelTestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tests': {
      id: '/_authenticated/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AuthenticatedAdminTestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestsRoute: typeof AuthenticatedAdminTestsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestsRoute: AuthenticatedAdminTestsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedWrittenRoute: typeof AuthenticatedWrittenRoute
  AuthenticatedModelTestIdRoute: typeof AuthenticatedModelTestIdRoute
  AuthenticatedPracticeSlugRoute: typeof AuthenticatedPracticeSlugRoute
  AuthenticatedModelTestIndexRoute: typeof AuthenticatedModelTestIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedWrittenRoute: AuthenticatedWrittenRoute,
  AuthenticatedModelTestIdRoute: AuthenticatedModelTestIdRoute,
  AuthenticatedPracticeSlugRoute: AuthenticatedPracticeSlugRoute,
  AuthenticatedModelTestIndexRoute: AuthenticatedModelTestIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
